# kind.yaml
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: control-plane
nodes:
- role: control-plane
  extraPortMappings:
  - containerPort: 30950
    hostPort: 30950
    listenAddress: "127.0.0.1"
    protocol: TCP
