#!/usr/bin/env bash

# PROJECT: window_manager
# Pick the Alacritty font size from the physical pixel pitch of the main screen
# and write it to the import file alacritty.toml pulls in. The same point size
# renders 16pt as 5mm glyphs on a 24" 1080p panel and 3.5mm on a 32" 4k panel,
# so one number in alacritty.toml fits exactly one desk. Targeting a glyph
# height in millimetres makes every desk come out the same size. Alacritty
# reloads imports live, so running windows resize as soon as the file changes.
#
# Usage: __alacritty_font_scale.sh [--print]
#   --print   show the computed size, write nothing
# Env:
#   ALACRITTY_FONT_MM   target glyph height in mm (default 4.6)
#   ALACRITTY_FONT_BASE size used when the screen reports no physical size

set -eo pipefail
IFS=$'\n\t'

source "$(dirname "${BASH_SOURCE[0]}")/__lib_screen.sh"

FONT_FILE="${ALACRITTY_FONT_FILE:-$HOME/.config/alacritty/font-size.toml}"
TARGET_MM="${ALACRITTY_FONT_MM:-4.6}"
BASE_SIZE="${ALACRITTY_FONT_BASE:-16.0}"
MIN_SIZE=8
MAX_SIZE=28

# Alacritty on X11 scales points by Xft.dpi (96 when unset).
xft_dpi() {
	local dpi
	dpi=$(xrdb -query 2>/dev/null | awk -F'\t' '$1 == "Xft.dpi:" { print $2; exit }')
	printf '%s\n' "${dpi:-96}"
}

# Print the font size in points, rounded to the nearest half point.
compute_font_size() {
	local mon name mm_per_px dpi
	mon=$(get_target_monitor) || { printf '%s\n' "$BASE_SIZE"; return 0; }
	name="${mon%% *}"
	mm_per_px=$(get_monitor_mm_per_px "$name") || { printf '%s\n' "$BASE_SIZE"; return 0; }
	dpi=$(xft_dpi)
	awk -v mm="$TARGET_MM" -v pitch="$mm_per_px" -v dpi="$dpi" -v lo="$MIN_SIZE" -v hi="$MAX_SIZE" 'BEGIN {
		px = mm / pitch
		pt = px * 72 / dpi
		pt = int(pt * 2 + 0.5) / 2
		if (pt < lo) pt = lo
		if (pt > hi) pt = hi
		printf "%.1f\n", pt
	}'
}

# Write the import file only when the size changed, so repeated calls (every
# layout keypress) never trigger a reload.
write_font_file() {
	local size="$1" content
	content=$(printf '# Generated by __alacritty_font_scale.sh. Do not edit.\n[font]\nsize = %s\n' "$size")
	if [[ -f "$FONT_FILE" ]] && [[ "$(<"$FONT_FILE")" == "$content" ]]; then
		return 0
	fi
	mkdir -p "$(dirname "$FONT_FILE")"
	printf '%s\n' "$content" > "$FONT_FILE"
}

main() {
	local size
	size=$(compute_font_size)
	if [[ "${1:-}" == "--print" ]]; then
		printf '%s\n' "$size"
		return 0
	fi
	write_font_file "$size"
}

if [[ "${BASH_SOURCE[0]}" == "$0" ]]; then
	main "$@"
fi
