#!/usr/bin/env bash
set -eo pipefail

# Regenerate scripts/__fzf_bindings.conf, the index of keys that only exist once
# a picker is already open.
#
# WHY A GENERATED FILE AND NOT A CONFHELP REGEX SECTION: the useful row is
# "M-x ctrl-l", and the two halves live in different files. .tmux.conf says
# M-x runs __file_opener.sh; __file_opener.sh says ctrl-l jumps to a line.
# confhelp parses one line of one file at a time and cannot join them, so the
# join happens here and confhelp reads the result.
#
# Three ways a picker declares a key, all of them in use:
#   --bind 'ctrl-y:execute(...)'      inline
#   COPY_BIND="ctrl-y:execute(...)"   assigned, used later as --bind "$COPY_BIND"
#   --expect=ctrl-l                   returned to the caller instead of run
# Parsing only the first (the original attempt) missed most of __file_opener.sh
# and all of M-x's ctrl-l, which is the binding this index exists for.

DOTFILES="${DOTFILES:-$HOME/dev/dotfiles}"
TMUX_CONF="$DOTFILES/.tmux.conf"
OUT="${1:-$DOTFILES/scripts/__fzf_bindings.conf}"

# script basename -> the tmux key that launches it, so a row can be found by the
# key actually remembered rather than by a filename nobody recalls.
declare -A LAUNCH
while IFS= read -r line; do
    [[ "$line" =~ ^bind ]] || continue
    key=$(sed -E "s/^bind(-key)?[[:space:]]+(-[a-zA-Z]+[[:space:]]+)*//; s/^'?([^'[:space:]]+)'?.*/\1/" <<< "$line")
    [[ -n "$key" ]] || continue
    while read -r script; do
        [[ -n "$script" ]] && LAUNCH["$(basename "$script")"]="$key"
    done < <(grep -oE '[^ "'"'"']*/scripts/__[a-zA-Z0-9_-]+\.sh' <<< "$line" || true)
done < "$TMUX_CONF"

{
    echo "# Generated by __fzf_bindings_gen.sh. Do not edit; rerun the generator."
    echo "# <launch-key> <sub-key>;<action>  <abs-path>:<line>"
    for f in "$DOTFILES"/scripts/*.sh; do
        base=$(basename "$f")
        [[ "$base" == "__fzf_bindings_gen.sh" ]] && continue
        prefix="${LAUNCH[$base]:-${base%.sh}}"
        n=0
        while IFS= read -r entry; do
            lineno="${entry%%:*}"
            rest="${entry#*:}"
            keys="${rest%%$'\t'*}"
            action="${rest#*$'\t'}"
            for k in ${keys//,/ }; do
                printf '%s %s;%s  %s:%s\n' "$prefix" "$k" "${action:0:70}" "$f" "$lineno"
                n=$((n + 1))
            done
        done < <(
            grep -nE -- "--bind[= ]['\"]?((ctrl|alt|shift)-[a-zA-Z0-9-]+|tab|enter|esc|f[0-9]+):" "$f" 2>/dev/null |
                sed -E "s/^([0-9]+):.*--bind[= ]['\"]?((ctrl|alt|shift)-[a-zA-Z0-9-]+|tab|enter|esc|f[0-9]+):(.*)/\1:\2\t\4/"
            grep -nE -- "^[[:space:]]*[A-Z_]+=['\"]((ctrl|alt|shift)-[a-zA-Z0-9-]+|tab|enter|esc|f[0-9]+):" "$f" 2>/dev/null |
                sed -E "s/^([0-9]+):[[:space:]]*[A-Z_]+=['\"]((ctrl|alt|shift)-[a-zA-Z0-9-]+|tab|enter|esc|f[0-9]+):(.*)/\1:\2\t\4/"
            grep -nE -- "--expect=[a-zA-Z0-9,-]+" "$f" 2>/dev/null |
                sed -E "s/^([0-9]+):.*--expect=([a-zA-Z0-9,-]+).*/\1:\2\treturned to the caller (--expect)/"
        )
    done
} > "$OUT"

printf 'wrote %s (%s bindings)\n' "$OUT" "$(grep -vc '^#' "$OUT")"
