---
apiVersion: v1
kind: Secret
metadata:
  name: azure-creds
  namespace: upbound-system
type: Opaque
data:
  creds: $base64encoded_azure_creds
---
apiVersion: azure.upbound.io/v1beta1
kind: ProviderConfig
metadata:
  name: provider-azure
spec:
  credentials:
    source: Secret
    secretRef:
      namespace: upbound-system
      name: azure-creds
      key: creds
