[colors.bright]
black = "#7c7c7c"
blue = "#b5dcfe"
cyan = "#dfdffe"
green = "#ceffab"
magenta = "#ff9cfe"
red = "#ffb6b0"
white = "#ffffff"
yellow = "#ffffcb"

[colors.cursor]
cursor = "#ffffff"
text = "#ffffff"

[colors.normal]
black = "#4e4e4e"
blue = "#96cbfe"
cyan = "#c6c5fe"
green = "#a8ff60"
magenta = "#ff73fd"
red = "#ff6c60"
white = "#eeeeee"
yellow = "#ffffb6"

[colors.primary]
background = "#000000"
foreground = "#ffffff"
