import = ["/home/decoder/.config/alacritty/themes/dracula.toml"]
live_config_reload = true

[keyboard]
bindings = [
  { key = "P", chars = "\u0002w", mods = "Command" },
  { key = "I", chars = "\u001B[105;5u", mods = "Control" },
  { key = "Space", action = "ToggleViMode", mode = "~Search", mods = "Shift|Control" },
  { key = "Y", action = "Copy", mode = "Vi|~Search" },
  { key = "Insert", action = "Paste", mods = "Shift" },
  { key = "H", action = "High", mode = "Vi|~Search", mods = "Shift" },
  { key = "M", action = "Middle", mode = "Vi|~Search", mods = "Shift" },
  { key = "L", action = "Low", mode = "Vi|~Search", mods = "Shift" },
]


[[hints.enabled]]
command = "xdg-open"
hyperlinks = true
post_processing = true
persist = false
mouse.enabled = true
binding = { key = "1", mods = "Control" }
regex = "(ipfs:|ipns:|magnet:|mailto:|gemini://|gopher://|https://|http://|news:|file:|git://|ssh:|ftp://)[^\u0000-\u001F\u007F-\u009F<>\"\\s{-}\\^⟨⟩`]+"

[cursor.style]
shape = "Block"

[env]
TERM = "xterm-256color"

[font]
builtin_box_drawing = true
size = 16.0

[font.bold]
style = "Bold"

[font.italic]
style = "Bold Italic"

[font.normal]
family = "JetbrainsMono Nerd Font"
style = "Regular"

[font.offset]
x = 0
y = 0


[[mouse.bindings]]
action = "Copy"
mouse = "Right"

[scrolling]
history = 10000

[window]
decorations = "none"
opacity = 1.0
startup_mode = "Maximized"

[window.dimensions]
columns = 133
lines = 40

[window.padding]
x = 5
y = 5
