import = ["/home/decoder/.config/alacritty/themes/dracula.toml"]
live_config_reload = true

[cursor.style]
shape = "Block"

[env]
TERM = "xterm-256color"

[font]
builtin_box_drawing = true
size = 16.0

[font.bold]
style = "Bold"

[font.italic]
style = "Bold Italic"

[font.normal]
family = "JetbrainsMono Nerd Font"
style = "Regular"

[font.offset]
x = 0
y = 0

[[keyboard.bindings]]
chars = "\u0002w"
key = "P"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001B[105;5u"
key = "I"
mods = "Control"

[[keyboard.bindings]]
action = "ToggleViMode"
key = "Space"
mode = "~Search"
mods = "Shift|Control"

[[keyboard.bindings]]
action = "Copy"
key = "Y"
mode = "Vi|~Search"

[[keyboard.bindings]]
action = "High"
key = "H"
mode = "Vi|~Search"
mods = "Shift"

[[keyboard.bindings]]
action = "Middle"
key = "M"
mode = "Vi|~Search"
mods = "Shift"

[[keyboard.bindings]]
action = "Low"
key = "L"
mode = "Vi|~Search"
mods = "Shift"

[[keyboard.bindings]]
action = "Paste"
key = "Insert"
mods = "Shift"

[[mouse.bindings]]
action = "Copy"
mouse = "Right"

[scrolling]
history = 10000

[window]
decorations = "none"
opacity = 1.0
startup_mode = "Maximized"

[window.dimensions]
columns = 133
lines = 40

[window.padding]
x = 5
y = 5
