require("plugins")
require("settings")
require("autocommands")
require("mappings")
require("telescope-setup")
require("lsp")
-- require("lsp-setup")
require("which-key-setup")
require("user_functions")
require("tags")
