require("plugins")
require("settings")
require("autocommands")
require("mappings")
require("telescope-setup")
require("hydra-setup")
-- require('xlpls-linter')
require("lsp-setup")
require("which-key-setup")

