# .github/workflows/test_workflow.yml
name: Run Tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Set up Bash
      run: |
        echo "BASH_VERSION=${BASH_VERSION}" >> $GITHUB_ENV

    - name: Run tests
      working-directory: scripts
      run: bash __detect_os_tests.sh

